// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHK7z54VPoDm7NYPCACAU5dZ_U4DD0YXc',
    appId: '1:716793905434:web:5df7127257b38f0a586ca3',
    messagingSenderId: '716793905434',
    projectId: 'byit-d039e',
    authDomain: 'byit-d039e.firebaseapp.com',
    storageBucket: 'byit-d039e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4R4iHeVlq-4FHTyYBfYUxXbiLJJ5GPbM',
    appId: '1:716793905434:android:70fad38bdc0a6109586ca3',
    messagingSenderId: '716793905434',
    projectId: 'byit-d039e',
    storageBucket: 'byit-d039e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvyVTZdRuHdwCu_vMhZS32ITCz3cqRzGI',
    appId: '1:716793905434:ios:b7d80763da65b82a586ca3',
    messagingSenderId: '716793905434',
    projectId: 'byit-d039e',
    storageBucket: 'byit-d039e.firebasestorage.app',
    iosBundleId: 'com.example.byit',
  );
}
